name: Docker Image CI

on:
  push:
    branches: [ "pi" ]
  pull_request:
    branches: [ "pi" ]
    
env:
  SEAFILE_VERSION: 9.0.2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Copy files
      run: cp -rf ./image/seafile_9.0/** ./
    - name: Build and Push
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        file: ./image/seafile_9.0/Dockerfile
        platforms: linux/arm64
        push: true
        cache-from: type=registry,ref=jmujmu/seafile-pi:buildcache
        cache-to: type=registry,ref=jmujmu/seafile-pi:buildcache,mode=max
        tags: jmujmu/seafile-pi:${{ env.SEAFILE_VERSION }}
